---

- name: Include task to setup the remote device
  include: setup.yaml

- name: Create Self IP
  bigip_selfip:
      address: "{{ selfip }}"
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      vlan: "{{ selfip_vlan }}"
  register: result

- name: Assert Create Self IP
  assert:
      that:
          - result|changed

- name: Create Self IP - Idempotent check
  bigip_selfip:
      address: "{{ selfip }}"
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      vlan: "{{ selfip_vlan }}"
  register: result

- name: Assert Create Self IP - Idempotent check
  assert:
      that:
          - not result|changed

- name: Create Self IP, specify a Route Domain
  bigip_selfip:
      address: "{{ selfip }}"
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      vlan: "{{ selfip_vlan }}"
      route_domain: "{{ selfip_rd }}"
  register: result

- name: Assert Create Self IP, specify a Route Domain
  assert:
      that:
          - result|changed

- name: Create Self IP, specify a Route Domain - Idempotent check
  bigip_selfip:
      address: "{{ selfip }}"
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      vlan: "{{ selfip_vlan }}"
      route_domain: "{{ selfip_rd }}"
  register: result

- name: Assert Create Self IP, specify a Route Domain - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set Self IP VLAN
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      vlan: "{{ selfip_vlan2 }}"
  register: result

- name: Assert Set Self IP VLAN
  assert:
      that:
          - result|changed

- name: Set Self IP VLAN - Idempotent check
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      vlan: "{{ selfip_vlan2 }}"
  register: result

- name: Assert Set Self IP VLAN - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set Self IP netmask
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set Self IP netmask
  assert:
      that:
          - result|changed

- name: Set Self IP netmask - Idempotent check
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set Self IP netmask - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set single protocol allow service
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      allow_service: "{{ allowed_services_single }}"
  register: result

- name: Assert Set single protocol allow service
  assert:
      that:
          - result|changed

- name: Set single protocol allow service - Idempotent check
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      allow_service: "{{ allowed_services_single }}"
  register: result

- name: Assert Set single protocol allow service - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set multiple protocol allow all service
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      allow_service: "{{ allowed_services_multi }}"
  register: result

- name: Assert Set multiple protocol allow all service
  assert:
      that:
          - result|changed

- name: Set multiple protocol allow all service - Idempotent check
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      allow_service: "{{ allowed_services_multi }}"
  register: result

- name: Assert Set multiple protocol allow all service - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set keyword "all" allow service
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      allow_service:
          - "all"
  register: result

- name: Assert Set keyword "all" allow service
  assert:
      that:
          - result|changed

- name: Set keyword "all" allow service - Idempotent check
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      allow_service:
          - "all"
  register: result

- name: Assert Set keyword "all" allow service - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set keyword "default" allow service
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      allow_service:
          - "default"
  register: result

- name: Assert Set keyword "default" allow service
  assert:
      that:
          - result|changed

- name: Set keyword "default" allow service - Idempotent check
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      allow_service:
          - "default"
  register: result

- name: Assert Set keyword "default" allow service - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set keyword "none" allow service
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      allow_service:
          - "none"
  register: result

- name: Assert Set keyword "none" allow service
  assert:
      that:
          - result|changed

- name: Set keyword "none" allow service - Idempotent check
  bigip_selfip:
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask2 }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      allow_service:
          - "none"
  register: result

- name: Assert Set keyword "none" allow service - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete Self IP
  bigip_selfip:
      name: "{{ selfip_name }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Delete Self IP
  assert:
      that:
          - result|changed

- name: Delete Self IP - Idempotent check
  bigip_selfip:
      name: "{{ selfip_name }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Delete Self IP - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete Self IP, specify a Route Domain
  bigip_selfip:
      name: "{{ selfip_name }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      route_domain: "{{ selfip_rd }}"
  register: result

- name: Assert Delete Self IP, specify a Route Domain
  assert:
      that:
          - result|changed

- name: Delete Self IP, specify a Route Domain - Idempotent check
  bigip_selfip:
      name: "{{ selfip_name }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      rd: "{{ selfip_rd }}"
  register: result

- name: Assert Delete Self IP, specify a Route Domain - Idempotent check
  assert:
      that:
          - not result|changed

- name: Create Self IP, specify a traffic group
  bigip_selfip:
      address: "{{ selfip }}"
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      traffic_group: "{{ default_traffic_group }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      vlan: "{{ selfip_vlan }}"
  register: result

- name: Assert Create Self IP, specify a traffic group
  assert:
      that:
          - result|changed

- name: Create Self IP, specify a traffic group - Idempotent check
  bigip_selfip:
      address: "{{ selfip }}"
      name: "{{ selfip_name }}"
      netmask: "{{ selfip_netmask }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      traffic_group: "{{ default_traffic_group }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      vlan: "{{ selfip_vlan }}"
  register: result

- name: Assert Create Self IP, specify a traffic group - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete Self IP that specified traffic group
  bigip_selfip:
      name: "{{ selfip_name }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Delete Self IP that specified traffic group
  assert:
      that:
          - result|changed
