---

# Test the bigip_monitor_tcp module
#
# Running this playbook assumes that you have a BIG-IP installation at the
# ready to receive the commands issued in this Playbook.
#
# This module will run tests against a BIG-IP host to verify that the
# bigip_monitor_tcp module behaves as expected.
#
# Usage:
#
#    ansible-playbook -i notahost, tests/bigip_monitor_tcp.yaml
#
# Examples:
#
#    Run all tests on the bigip_monitor_tcp module
#
#    ansible-playbook -i notahost, tests/bigip_monitor_tcp.yaml
#
# Tested platforms:
#
#    - 12.0.0
#

- name: Test the bigip_monitor_tcp module
  hosts: f5-test
  connection: local

  roles:
      - __bigip_monitor_tcp