---

# Test the iworkflow_license_pool_member module
#
# Running this playbook assumes that you have a BIG-IP installation at the
# ready to receive the commands issued in this Playbook.
#
# This module will run tests against a BIG-IP host to verify that the
# iworkflow_license_pool_member module behaves as expected.
#
# Usage:
#
#    ansible-playbook -i notahost, playbooks/iworkflow_license_pool_member.yaml
#
# Examples:
#
#    Run all tests on the iworkflow_license_pool_member module
#
#    ansible-playbook -i notahost, playbooks/iworkflow_license_pool_member.yaml
#
# Tested platforms:
#
#    - NA
#

- name: Test the iworkflow_license_pool_member module
  hosts: f5-test
  connection: local

  roles:
<<<<<<< HEAD
      - __iworkflow_license_pool_member
=======
      - iworkflow_license_pool_member
>>>>>>> master
